### ISSUE TITLE
Code style guides - A importância de manter um padrão de código

### ISSUE THREAD

**Issue by viniciusdacal** [JSdayBR/jsdaybr.github.io#10]
![11282_443222935750959_441847382_n](https://cloud.githubusercontent.com/assets/2660570/9705715/81351f18-54a4-11e5-82a1-978f4e880dd8.jpg)

**Vinicius Dacal**
Frontend Developer, Coderockr

**Resumo:**
Como manter um código legível e consistente em um projeto com mais de 100 arquivos JS e uma equipe com diferentes níveis de experiência e diferentes backgrounds? Nesta talk vou mostrar algumas decisões que tomamos dentro da Coderockr para manter um padrão de código em todo o projeto em um ambiente de integração contínua.

**Mini-bio:**
Começou a fazer websites por diversão com 14 anos e aos 18 anos fez disso a sua profissão. Graduado em  Sistemas para Internet, adora participar de eventos de desenvolvimento e contribuir com projetos Open Source.

**Cidade:**
Joinville/Sc

**Comment by juarezpaf** [comment]
Muito obrigado Vinicius pela sua submissão, vamos te esperar no próximo hein? Abração! :rocket:
