### ISSUE TITLE
I promise you: Como sair do inferno de callbacks para a glória das Promises.

### ISSUE THREAD

**Issue by wbruno** [JSdayBR/jsdaybr.github.io#4]
**Palestrante**
![William Bruno](https://avatars0.githubusercontent.com/u/1443932?v=3&s=300)
William Bruno @wbruno
Desenvolvedor NodeJS - Walmart.com

**Resumo**
Seja no client-side ou no server-side, a dificuldade de trabalharmos com requisições assíncronas é algo que facilmente pode nos levar a ter diversos callbacks aninhados. Pode sair de controle quando temos diversas requisições que dependem uma da outra, e o nosso código vai ganhando mais e mais níveis de indentação. Utilizando Promises A+ já disponíveis através da ES6 ou libs de pollyfil, podemos transformar essa dor de cabeça numa organização ao estilo programação funcional e novamente conseguirmos nos encontrar no nosso próprio código.

**Mini bio**
William Bruno é desenvolvedor web apaixonado por boas práticas e design patterns. Iniciou com programação web em 2008 com PHP e JavaScript. Participante ativo do Fórum iMasters, escreve artigos para seu blog pessoal e alguns outros canais. Atualmente trabalha no Walmart.com com NodeJS.

**Cidade**
São Paulo/SP

**Comment by wbruno** [comment]
Não tenho permissão para colocar label e milestone

**Comment by juarezpaf** [comment]
Muito obrigado William pela sua submissão, vamos te esperar no próximo hein? Abração! :rocket:
