### ISSUE TITLE
Aplicações móveis multi-plataforma com Titanium Mobile

### ISSUE THREAD

**Issue by ecavalcanti** [JSdayBR/jsdaybr.github.io#7]
**Palestrante:**
![foto](https://cloud.githubusercontent.com/assets/2058073/9701995/b9cc743c-541f-11e5-8f56-28c0dbe67cd7.jpg)

Eric Cavalcanti
Software Engineer, CESAR

**Resumo:**
O Titanium Mobile é um framework open source para desenvolvimento de aplicações móveis multi-plataforma, usando uma única linguagem de programação, o JavaScript. Com este framework você poderá criar aplicativos com a aparência e comportamento nativos para as plataformas iOS, Android e Windows Phone.

**Mini-bio:**
Atua no C.E.S.A.R. como Engenheiro de Software e como professor do Curso de Especialização em Tecnologias para Desenvolvimento de Aplicações Móveis, além de ser Mestre em Engenharia de Software. Possui o Titanium Certified App Developer (TCAD), integrante do grupo Titans da Appcelerator, possui 19 anos de experiência na área de TI, dedicados ao desenvolvimento de aplicações web, móveis e desktop.

**Cidade:**
Recife/PE

**Comment by juarezpaf** [comment]
Muito obrigado Eric pela sua submissão, vamos te esperar no próximo hein? :rocket:
